version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8000:8000"
    environment:
      - ml_backend_DB__uri=postgresql://postgres:postgres@db:5432/ml_backend
      - ml_backend_DB__connect_args={}
    volumes:
      - .:/home/app/web
    depends_on:
      - db
  db:
    build: postgres
    image: ml_backend_postgres-13-alpine-multi-user
    volumes:
      - $HOME/.postgres/ml_backend_db/data/postgresql:/var/lib/postgresql/data
    ports:
      - 5435:5432
    environment:
      - POSTGRES_DBS=ml_backend, ml_backend_test
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
